N05~Forum/N05~Forum/MVCForum.Website/ViewModels/CategoryViewModels.cs
using System.Collections.Generic;
using System.Web.Mvc;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.ViewModels
{
    public class BreadcrumbViewModel
    {
        public List<Category> Categories { get; set; }
        public Topic Topic { get; set; }
        public Category Category { get; set; }
    }

    public class CategoryListViewModel
    {
        public Dictionary<Category, PermissionSet> AllPermissionSets { get; set; }
    }

    public class CategoryRowViewModel
    {
        public Category Category { get; set; }
        public int TopicCount { get; set; }
        public Topic LatestTopic { get; set; }
        public int PostCount { get; set; }
        public PermissionSet Permissions { get; set; }
    }

    public class ViewCategoryViewModel
    {
        public List<TopicViewModel> Topics { get; set; }
        public PermissionSet Permissions { get; set; }
        public Category Category { get; set; }
        public CategoryListViewModel SubCategories { get; set; }
        public MembershipUser User { get; set; }
        public bool IsSubscribed { get; set; }

        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
        public int? TotalPages { get; set; }
    }

    public class SubCategoryViewModel
    {
        public Dictionary<Category, PermissionSet> AllPermissionSets { get; set; }
        public Category ParentCategory { get; set; }
    }

}

N05~Forum/N05~Forum/MVCForum.Website/Controllers/CategoryController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Application;
using MVCForum.Website.ViewModels;
using System.Linq;
using MVCForum.Website.ViewModels.Mapping;

namespace MVCForum.Website.Controllers
{
    public partial class CategoryController : BaseController
    {
        private readonly ICategoryService _categoryService;
        private readonly ICategoryNotificationService _categoryNotificationService;
        private readonly ITopicService _topicService;
        private readonly IPollAnswerService _pollAnswerService;
        private readonly ITopicNotificationService _topicNotificationService;
        private readonly IVoteService _voteService;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="loggingService"> </param>
        /// <param name="unitOfWorkManager"> </param>
        /// <param name="membershipService"></param>
        /// <param name="localizationService"></param>
        /// <param name="roleService"></param>
        /// <param name="categoryService"></param>
        /// <param name="settingsService"> </param>
        /// <param name="topicService"> </param>
        /// <param name="categoryNotificationService"> </param>
        public CategoryController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager,
            IMembershipService membershipService,
            ILocalizationService localizationService,
            IRoleService roleService,
            ICategoryService categoryService,
            ISettingsService settingsService, ITopicService topicService, ICategoryNotificationService categoryNotificationService, IPollAnswerService pollAnswerService, ITopicNotificationService topicNotificationService, IVoteService voteService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _categoryService = categoryService;
            _topicService = topicService;
            _categoryNotificationService = categoryNotificationService;
            _pollAnswerService = pollAnswerService;
            _topicNotificationService = topicNotificationService;
            _voteService = voteService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult ListMainCategories()
        {
            var catViewModel = new CategoryListViewModel
            {
                AllPermissionSets = new Dictionary<Category, PermissionSet>()
            };

            using (UnitOfWorkManager.NewUnitOfWork())
            {
                foreach (var category in _categoryService.GetAllMainCategories())
                {
                    var permissionSet = RoleService.GetPermissions(category, UsersRole);
                    catViewModel.AllPermissionSets.Add(category, permissionSet);
                }
            }

            return PartialView(catViewModel);
        }

        [ChildActionOnly]
        public PartialViewResult ListCategorySideMenu()
        {
            var catViewModel = new CategoryListViewModel
            {
                AllPermissionSets = new Dictionary<Category, PermissionSet>()
            };
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                foreach (var category in _categoryService.GetAll())
                {
                    var permissionSet = RoleService.GetPermissions(category, UsersRole);
                    catViewModel.AllPermissionSets.Add(category, permissionSet);
                }
            }

            return PartialView(catViewModel);
        }

        [Authorize]
        [ChildActionOnly]
        public PartialViewResult GetSubscribedCategories()
        {
            var viewModel = new List<CategoryRowViewModel>();
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var categories = LoggedOnReadOnlyUser.CategoryNotifications.Select(x => x.Category);
                foreach (var category in categories)
                {
                    var permissionSet = RoleService.GetPermissions(category, UsersRole);
                    var topicCount = category.Topics.Count;
                    var latestTopicInCategory = category.Topics.OrderByDescending(x => x.LastPost.DateCreated).FirstOrDefault();
                    var postCount = (category.Topics.SelectMany(x => x.Posts).Count() - 1);
                    var model = new CategoryRowViewModel
                    {
                        Category = category,
                        LatestTopic = latestTopicInCategory,
                        Permissions = permissionSet,
                        PostCount = postCount,
                        TopicCount = topicCount
                    };
                    viewModel.Add(model);
                }
            }

            return PartialView(viewModel);
        }


        [ChildActionOnly]
        public PartialViewResult GetCategoryBreadcrumb(Category category)
        {
            var allowedCategories = _categoryService.GetAllowedCategories(UsersRole);

            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new BreadcrumbViewModel
                {
                    Categories = _categoryService.GetCategoryParents(category,allowedCategories),
                    Category = category
                };
                return PartialView("GetCategoryBreadcrumb", viewModel);
            }
        }

        public ActionResult Show(string slug, int? p)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                // Get the category
                var category = _categoryService.GetBySlugWithSubCategories(slug);

                // Allowed Categories for this user
                var allowedCategories = _categoryService.GetAllowedCategories(UsersRole);

                // Set the page index
                var pageIndex = p ?? 1;

                // check the user has permission to this category
                var permissions = RoleService.GetPermissions(category.Category, UsersRole);

                if (!permissions[AppConstants.PermissionDenyAccess].IsTicked)
                {

                    var topics = _topicService.GetPagedTopicsByCategory(pageIndex,
                                                                        SettingsService.GetSettings().TopicsPerPage,
                                                                        int.MaxValue, category.Category.Id);

                    var topicViewModels = ViewModelMapping.CreateTopicViewModels(topics.ToList(), RoleService, UsersRole, LoggedOnReadOnlyUser, allowedCategories, SettingsService.GetSettings());

                    // Create the main view model for the category
                    var viewModel = new ViewCategoryViewModel
                        {
                            Permissions = permissions,
                            Topics = topicViewModels,
                            Category = category.Category,
                            PageIndex = pageIndex,
                            TotalCount = topics.TotalCount,
                            TotalPages = topics.TotalPages,
                            User = LoggedOnReadOnlyUser,
                            IsSubscribed = UserIsAuthenticated && (_categoryNotificationService.GetByUserAndCategory(LoggedOnReadOnlyUser, category.Category).Any())
                        };

                    // If there are subcategories then add then with their permissions
                    if (category.SubCategories.Any())
                    {
                        var subCatViewModel = new CategoryListViewModel
                            {
                                AllPermissionSets = new Dictionary<Category, PermissionSet>()
                            };
                        foreach (var subCategory in category.SubCategories)
                        {
                            var permissionSet = RoleService.GetPermissions(subCategory, UsersRole);
                            subCatViewModel.AllPermissionSets.Add(subCategory, permissionSet);
                        }
                        viewModel.SubCategories = subCatViewModel;
                    }

                    return View(viewModel);
                }

                return ErrorToHomePage(LocalizationService.GetResourceString("Errors.NoPermission"));
            }
        }

        [OutputCache(Duration = AppConstants.ShortCacheTime)]
        public ActionResult CategoryRss(string slug)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {


                // get an rss lit ready
                var rssTopics = new List<RssItem>();

                // Get the category
                var category = _categoryService.Get(slug);

                // check the user has permission to this category
                var permissions = RoleService.GetPermissions(category, UsersRole);

                if (!permissions[AppConstants.PermissionDenyAccess].IsTicked)
                {
                    var topics = _topicService.GetRssTopicsByCategory(SiteConstants.ActiveTopicsListSize, category.Id);

                    rssTopics.AddRange(topics.Select(x =>
                                                         {
                                                             var firstOrDefault =
                                                                 x.Posts.FirstOrDefault(s => s.IsTopicStarter);
                                                             return firstOrDefault != null
                                                                        ? new RssItem
                                                                              {

N05~Forum/N05~Forum/MVCForum.Website/Controllers/TagController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Utilities;
using MVCForum.Website.Application;
using MVCForum.Website.ViewModels;

namespace MVCForum.Website.Controllers
{
    public partial class TagController : BaseController
    {
        private readonly ITopicTagService _topicTagService;
        private readonly ICategoryService _categoryService;
        private readonly ICacheService _cacheService;

        public TagController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService, IRoleService roleService, ISettingsService settingsService, ITopicTagService topicTagService, ICategoryService categoryService, ICacheService cacheService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _topicTagService = topicTagService;
            _categoryService = categoryService;
            _cacheService = cacheService;
        }

        [ChildActionOnly]
        public PartialViewResult PopularTags(int amountToTake)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                PopularTagViewModel viewModel;
                var cacheKey = string.Concat("PopularTags", amountToTake, UsersRole.Id);
                var cachedData = _cacheService.Get(cacheKey);
                if (cachedData == null)
                {
                    var allowedCategories = _categoryService.GetAllowedCategories(UsersRole);
                    var popularTags = _topicTagService.GetPopularTags(amountToTake, allowedCategories);
                    viewModel = new PopularTagViewModel { PopularTags = popularTags };   
                    _cacheService.Set(cacheKey, viewModel, AppConstants.LongCacheTime);
                }
                else
                {
                    viewModel = (PopularTagViewModel) cachedData;
                }
                return PartialView(viewModel);
            }
        }

        [HttpGet]
        public JsonResult AutoCompleteTags(string term)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var toReturn = string.Empty;
                var returnList = new List<string>();
                var tags = _topicTagService.GetContains(term);

                if (!tags.Any())
                {
                    return Json(returnList, JsonRequestBehavior.AllowGet);
                }

                foreach (var topicTag in tags)
                {
                    toReturn += string.Format("\"{0}\",", topicTag.Tag);
                    returnList.Add(topicTag.Tag);
                }

                return Json(returnList, JsonRequestBehavior.AllowGet);
                
            }
        }

    }
}

N05~Forum/N05~Forum/MVCForum.Website/Views/Category/GetSubscribedCategories.cshtml
@model List<MVCForum.Website.ViewModels.CategoryRowViewModel>
        
@if (Model.Any())
{
    foreach (var catModel in Model)
    {
        @Html.Partial("_Category", catModel)
    }
}
else
{
    <p>@Html.Lang("SubscribedCats.NothingToShow")</p>
}

N05~Forum/N05~Forum/MVCForum.Website/Views/Category/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutRightSideBar.cshtml";
    ViewBag.Title = Html.Raw(Html.LanguageString("Category.AllCategories"));
}
@section side
{
    @Html.Action("SideSearch", "Search")
    @Html.Action("PopularTags", "Tag", new { amountToTake = 20})
    @Html.Action("CurrentWeekHighPointUsers", "Point")
}


@Html.Action("ListMainCategories", "Category")

N05~Forum/N05~Forum/MVCForum.Website/Views/Category/ListCategorySideMenu.cshtml
@model MVCForum.Website.ViewModels.CategoryListViewModel
@{
    var allCats = Model.AllPermissionSets.Keys;
}
<div class="side-box categories-box">
    <h5>@Html.LanguageString("Category.CategoriesSideHeading")</h5>

    <ul>
        <li><a href="@Url.Action("Index")">@Html.LanguageString("Category.AllCategories")</a></li>
        @foreach (var category in allCats.Where(x => x.ParentCategory == null))
        {
            var currentcatId = category.Id;
            var permissions = Model.AllPermissionSets[category];
            var subCats = allCats.Where(x => x.ParentCategory != null && x.ParentCategory.Id == currentcatId).ToList();
            if (!permissions[AppConstants.PermissionDenyAccess].IsTicked)
            {
                <li class="catitem">
                    <a style="border-color: @(string.IsNullOrEmpty(category.Colour) ? "#ced1d1" : category.Colour)" href="@Html.Raw(category.NiceUrl)">@Html.Raw(category.Name)</a>
                    @if (subCats.Any())
                    {
                        <ul>
                            @foreach (var subCat in subCats)
                            {
                                var subPermissions = Model.AllPermissionSets[subCat];
                                if (!subPermissions[AppConstants.PermissionDenyAccess].IsTicked)
                                {
                                    <li class="catitem">
                                        <a style="border-color: @(string.IsNullOrEmpty(subCat.Colour) ? "#ced1d1" : subCat.Colour)" href="@Html.Raw(subCat.NiceUrl)">@Html.Raw(subCat.Name)</a>
                                    </li>
                                }
                            }
                        </ul>
                    }

                </li>
            }
        }
    </ul>



</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/Category/ListMainCategories.cshtml
@using MVCForum.Website.ViewModels
@model CategoryListViewModel
@{
    Layout = null;
}
<div class="row">
    <div class="col-md-9">
        <h2>@ViewBag.Title</h2>
    </div>
</div>

<div class="categoryindex">

    @foreach (var cat in Model.AllPermissionSets.Keys)
    {
        var permissions = Model.AllPermissionSets[cat];
        var topicCount = cat.Topics.Count;
        var latestTopicInCategory = cat.Topics.OrderByDescending(x => x.LastPost.DateCreated).FirstOrDefault();
        var actualPostCount = cat.Topics.SelectMany(x => x.Posts).Count();
        var postCount = (actualPostCount < 1 ? actualPostCount : actualPostCount - 1);

        @Html.Partial("_Category", new CategoryRowViewModel
                                       {
                                           Category = cat,
                                           LatestTopic = latestTopicInCategory,
                                           Permissions = permissions,
                                           PostCount = postCount,
                                           TopicCount = topicCount
                                       })

    }

</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/Category/Show.cshtml
@using MVCForum.Utilities
@using MVCForum.Website.ViewModels
@model ViewCategoryViewModel
@{
    Layout = "~/Views/Shared/_LayoutRightSideBar.cshtml";
    ViewBag.Title = Html.Raw(Model.Category.PageTitle ?? Model.Category.Name);
    ViewBag.MetaDesc = Model.Category.MetaDescription ?? StringUtils.StripHtmlFromString(Model.Category.Description);
    var totalCount = Convert.ToInt32(Model.TotalCount);
    ViewBag.Canonical = Html.Raw(AppHelpers.CanonicalPagingTag(totalCount, Html.Settings().TopicsPerPage, Html));

    var subScribe = string.Empty;
    var unSubscribe = string.Empty;
    const string displayNone = "style='display:none;'";
    if (Model.IsSubscribed)
    {
        subScribe = displayNone;
    }
    else
    {
        unSubscribe = displayNone;
    }
    //TempData[AppConstants.DefaultCategoryViewBagName] = Model.Category.Id;
}
@section SocialMeta {
    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:url" content="@HttpContext.Current.Request.Url.AbsoluteUri" />
    <meta property="og:type" content="website" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="@ViewBag.Title" />
    <meta name="twitter:description" content="@ViewBag.MetaDesc" />
}
@section side
{
    @Html.Partial("_CommonSideNav")
}

@Html.Action("GetCategoryBreadcrumb", "Category", new { category = Model.Category })

<div class="category">

    <div class="mainheading clearfix">

        <div class="widgetright">
            @if (Html.Settings().EnableRSSFeeds)
            {
                <a title="@Html.LanguageString("Home.Rss")" href="@Url.Action("CategoryRss", "Category", new { slug = Model.Category.Slug })" class="rsssubscribe">
                    <i class="fa fa-rss-square orange-colour"></i>
                </a>
            }
            @if (Model.User != null && Html.Settings().EnableEmailSubscriptions)
            {
                <a @Html.Raw(subScribe) href="#" class="emailsubscription" data-id="@Model.Category.Id" data-type="category">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    @Html.LanguageString("Notification.Subscribe")
                </a>
                <a @Html.Raw(unSubscribe) href="#" class="emailunsubscription" data-id="@Model.Category.Id" data-type="category">
                    <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                    @Html.LanguageString("Notification.UnSubscribe")
                </a>
            }
        </div>
        @if (!string.IsNullOrEmpty(Model.Category.Image))
        {
            <img src="@AppHelpers.CategoryImage(Model.Category.Image, Model.Category.Id,110)" alt="@Model.Category" class="categoryimage" />
        }
        <h1>@Html.Raw(Model.Category.Name)</h1>
        <p>@Html.Raw(AppHelpers.ConvertPostContent(Model.Category.Description))</p>
    </div>

    @if (Model.SubCategories != null)
    {
        Html.RenderPartial("_SubCategories", new SubCategoryViewModel
            {
                AllPermissionSets = Model.SubCategories.AllPermissionSets,
                ParentCategory = Model.Category
            });
    }

    @if (Model.TotalCount > 0)
    {
        foreach (var topic in Model.Topics)
        {
            Html.RenderPartial("_Topic", topic);
        }

        if (Model.TotalPages > 1)
        {
            @Html.Pager(Convert.ToInt32(Model.PageIndex), Html.Settings().TopicsPerPage, totalCount, null)
        }
    }
    else
    {
        <p>@Html.LanguageString("Category.NoDiscussions")</p>
    }

</div>