N05~Forum/N05~Forum/MVCForum.Website/ViewModels/SearchViewModels.cs
using System.Collections.Generic;

namespace MVCForum.Website.ViewModels
{
    public class SearchViewModel
    {
        public List<PostViewModel> Posts { get; set; }
        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
        public int? TotalPages { get; set; }
        public string Term { get; set; }

    }
}

N05~Forum/N05~Forum/MVCForum.Website/Controllers/MembersController.cs
using System;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Security.Principal;
using System.Text;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Security;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.DomainModel.Enums;
using MVCForum.Domain.Events;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Utilities;
using MVCForum.Website.Application;
using MVCForum.Website.Areas.Admin.ViewModels;
using MVCForum.Website.ViewModels;
using MVCForum.Website.ViewModels.Mapping;
using MembershipCreateStatus = MVCForum.Domain.DomainModel.MembershipCreateStatus;
using MembershipUser = MVCForum.Domain.DomainModel.MembershipUser;

namespace MVCForum.Website.Controllers
{
    public partial class MembersController : BaseController
    {
        private readonly IPostService _postService;
        private readonly IReportService _reportService;
        private readonly IEmailService _emailService;
        private readonly IPrivateMessageService _privateMessageService;
        private readonly IBannedEmailService _bannedEmailService;
        private readonly IBannedWordService _bannedWordService;
        private readonly ITopicNotificationService _topicNotificationService;
        private readonly IPollAnswerService _pollAnswerService;
        private readonly IVoteService _voteService;
        private readonly ICategoryService _categoryService;

        public MembersController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService,
            IRoleService roleService, ISettingsService settingsService, IPostService postService, IReportService reportService, IEmailService emailService, IPrivateMessageService privateMessageService, IBannedEmailService bannedEmailService, IBannedWordService bannedWordService, ITopicNotificationService topicNotificationService, IPollAnswerService pollAnswerService, IVoteService voteService, ICategoryService categoryService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _postService = postService;
            _reportService = reportService;
            _emailService = emailService;
            _privateMessageService = privateMessageService;
            _bannedEmailService = bannedEmailService;
            _bannedWordService = bannedWordService;
            _topicNotificationService = topicNotificationService;
            _pollAnswerService = pollAnswerService;
            _voteService = voteService;
            _categoryService = categoryService;
        }

        [Authorize(Roles = AppConstants.AdminRoleName)]
        public ActionResult SrubAndBanUser(Guid id)
        {
            var user = MembershipService.GetUser(id);

            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                if (!user.Roles.Any(x => x.RoleName.Contains(AppConstants.AdminRoleName)))
                {
                    MembershipService.ScrubUsers(user, unitOfWork);

                    try
                    {
                        unitOfWork.Commit();
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Members.SuccessfulSrub"),
                            MessageType = GenericMessages.success
                        };
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Members.UnSuccessfulSrub"),
                            MessageType = GenericMessages.danger
                        };
                    }
                }
            }

            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = ViewModelMapping.UserToMemberEditViewModel(user);
                viewModel.AllRoles = RoleService.AllRoles();
                return Redirect(user.NiceUrl);
            }

        }

        [Authorize]
        public ActionResult BanMember(Guid id)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var user = MembershipService.GetUser(id);
                var permissions = RoleService.GetPermissions(null, UsersRole);

                if (permissions[AppConstants.PermissionEditMembers].IsTicked)
                {

                    if (!user.Roles.Any(x => x.RoleName.Contains(AppConstants.AdminRoleName)))
                    {
                        user.IsBanned = true;

                        try
                        {
                            unitOfWork.Commit();
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Members.NowBanned"),
                                MessageType = GenericMessages.success
                            };
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Error.UnableToBanMember"),
                                MessageType = GenericMessages.danger
                            };
                        }
                    }
                }

                return Redirect(user.NiceUrl);
            }
        }

        [Authorize]
        public ActionResult UnBanMember(Guid id)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var user = MembershipService.GetUser(id);
                var permissions = RoleService.GetPermissions(null, UsersRole);

                if (permissions[AppConstants.PermissionEditMembers].IsTicked)
                {
                    if (!user.Roles.Any(x => x.RoleName.Contains(AppConstants.AdminRoleName)))
                    {
                        user.IsLockedOut = false;

                        try
                        {
                            unitOfWork.Commit();
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Members.NowUnBanned"),
                                MessageType = GenericMessages.success
                            };
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Error.UnableToUnBanMember"),
                                MessageType = GenericMessages.danger
                            };
                        }
                    }
                }

                return Redirect(user.NiceUrl);
            }
        }


        [ChildActionOnly]
        public PartialViewResult GetCurrentActiveMembers()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new ActiveMembersViewModel
                {
                    ActiveMembers = MembershipService.GetActiveMembers()
                };
                return PartialView(viewModel);
            }
        }

        public JsonResult LastActiveCheck()
        {
            if (UserIsAuthenticated)
            {
                var rightNow = DateTime.UtcNow;
                var usersDate = LoggedOnReadOnlyUser.LastActivityDate ?? DateTime.UtcNow.AddDays(-1);

                var span = rightNow.Subtract(usersDate);
                var totalMins = span.TotalMinutes;

                if (totalMins > AppConstants.TimeSpanInMinutesToDoCheck)
                {
                    using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                    {
                        // Actually get the user, LoggedOnUser has no tracking
                        var loggedOnUser = MembershipService.GetUser(Username);

                        // Update users last activity date so we can show the latest users online
                        loggedOnUser.LastActivityDate = DateTime.UtcNow;

                        // Update
                        try
                        {
                            unitOfWork.Commit();
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                        }
                    }
                }
            }

            // You can return anything to reset the timer.
            return Json(new { Timer = "reset" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetByName(string slug)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var member = MembershipService.GetUserBySlug(slug);
                var loggedonId = UserIsAuthenticated ? LoggedOnReadOnlyUser.Id : Guid.Empty;

N05~Forum/N05~Forum/MVCForum.Website/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Utilities;
using MVCForum.Website.Application;
using MVCForum.Website.ViewModels;
using MVCForum.Website.ViewModels.Mapping;

namespace MVCForum.Website.Controllers
{
    public partial class SearchController : BaseController
    {
        private readonly IPostService _postService;
        private readonly ITopicService _topicsService;
        private readonly ICategoryService _categoryService;
        private readonly IVoteService _voteService;
        private readonly IFavouriteService _favouriteService;

        public SearchController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager,
            IMembershipService membershipService, ILocalizationService localizationService,
            IRoleService roleService, ISettingsService settingsService,
            IPostService postService, ITopicService topicService, IVoteService voteService, IFavouriteService favouriteService, ICategoryService categoryService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _postService = postService;
            _topicsService = topicService;
            _voteService = voteService;
            _favouriteService = favouriteService;
            _categoryService = categoryService;
        }

        [HttpGet]
        public ActionResult Index(int? p, string term)
        {
            if (!string.IsNullOrEmpty(term))
            {
                using (UnitOfWorkManager.NewUnitOfWork())
                {
                    if (!string.IsNullOrEmpty(term))
                    {
                        term = term.Trim();
                    }

                    // Get the global settings
                    var settings = SettingsService.GetSettings();

                    // Get allowed categories
                    var allowedCategories = _categoryService.GetAllowedCategories(UsersRole);


                    // Set the page index
                    var pageIndex = p ?? 1;

                    // Get all the topics based on the search value
                    var posts = _postService.SearchPosts(pageIndex,
                                                         SiteConstants.SearchListSize,
                                                         int.MaxValue,
                                                         term,
                                                         allowedCategories);

                    // Get all the permissions for these topics
                    var topicPermissions = ViewModelMapping.GetPermissionsForTopics(posts.Select(x => x.Topic), RoleService, UsersRole);

                    // Get the post Ids
                    var postIds = posts.Select(x => x.Id).ToList();

                    // Get all votes for these posts
                    var votes = _voteService.GetVotesByPosts(postIds);

                    // Get all favourites for these posts
                    var favs = _favouriteService.GetAllPostFavourites(postIds);

                    // Create the post view models
                    var viewModels = ViewModelMapping.CreatePostViewModels(posts.ToList(), votes, topicPermissions, LoggedOnReadOnlyUser, settings, favs);

                    // create the view model
                    var viewModel = new SearchViewModel
                    {
                        Posts = viewModels,
                        PageIndex = pageIndex,
                        TotalCount = posts.TotalCount,
                        TotalPages = posts.TotalPages,
                        Term = term
                    };

                    return View(viewModel);
                }
            }

            return RedirectToAction("Index", "Home");
        }


        [ChildActionOnly]
        public PartialViewResult SideSearch()
        {
            return PartialView();
        }

    }
}

N05~Forum/N05~Forum/MVCForum.Website/Views/Members/AdminMemberProfileTools.cshtml
@using MVCForum.Domain.Constants
@model MVCForum.Website.ViewModels.ViewMemberViewModel
<div class="adminprofiletools">
    
    @if(!Model.User.IsBanned)
    {
        <p><a href="@Url.Action("BanMember", "Members", new {id = Model.User.Id }, null)" class="btn-mvc">@Html.LanguageString("Members.BanUser")</a></p>
    }
    else
    {
        <p><a href="@Url.Action("UnBanMember", "Members", new {id = Model.User.Id }, null)" class="btn-mvc">@Html.LanguageString("Members.UnBanUser")</a></p>
    }

    <p><a href="@Url.Action("Edit", "Members", new { Model.User.Id }, null)" class="btn-mvc">@Html.LanguageString("Members.EditMember")</a></p>      

    @if (User.IsInRole(AppConstants.AdminRoleName))
    {
        <p><a href="@Url.Action("SrubAndBanUser", "Members", new { id = Model.User.Id }, null)" class="btn-mvc" onclick="return confirm('@Html.LanguageString("Confirmation.SrubAndBan")')">@Html.LanguageString("Members.SrubAndBan")</a></p> 
    }

</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/Members/ChangePassword.cshtml
@model MVCForum.Website.ViewModels.ChangePasswordViewModel

@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("Members.ChangePassword.Title");
}

<div class="row">

    <div class="col-md-6 col-md-offset-3">
        @using (Html.BeginForm("ChangePassword", "Members", FormMethod.Post, new { @class = "form-forgotpassword" }))
        {
            @Html.ValidationSummary(true)
            @Html.AntiForgeryToken()

            <fieldset>
                <legend>@ViewBag.Title</legend>

                <p>
                    @string.Format(Html.LanguageString("Members.ChangePassword.Text"), Membership.MinRequiredPasswordLength)
                </p>

                <div class="form-group">
                    @Html.LabelFor(m => m.OldPassword)
                    @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.OldPassword)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.NewPassword)
                    @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.NewPassword)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ConfirmPassword)
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ConfirmPassword)
                </div>

                <div class="submit-holder">
                    <button type="submit" class="btn-mvc-green btn-mvc-large">@Html.LanguageString("Buttons.ChangePassword")</button>
                </div>
            </fieldset>

        }
    </div>
</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/Members/Edit.cshtml
@using MVCForum.Website.Application.ExtensionMethods
@model MVCForum.Website.ViewModels.MemberFrontEndEditViewModel

@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = @Html.LanguageString("Members.EditProfile");
}
@section Header
{
    <script type="text/javascript">
        $.ajax({
            url: app_base + 'Badge/ProfileBadgeCheck',
            type: 'POST',
            error: function (xhr, ajaxOptions, thrownError) {
                ShowUserMessage("Error: " + xhr.status + " " + thrownError);
            }
        });
    </script>

}
<div class="row">

    <div class="col-md-6 col-md-offset-3">
        @using (Html.BeginForm("Edit", "Members", FormMethod.Post, new { enctype = "multipart/form-data", @class = "editmemberform" }))
        {
            @Html.HiddenFor(x => Model.Id)

            @Html.ValidationSummary(true)

            <fieldset>
                <legend>@ViewBag.Title</legend>

                <p class="changepasswordtext">
                    @Html.Raw(string.Format(Html.LanguageString("Members.ChangePassword.Link"), string.Format("<a href=\"{0}\">{1}</a>", Url.Action("ChangePassword"), Html.LanguageString("Members.ChangePassword.Title"))))
                </p>

                <div class="form-group">
                    @Html.LabelFor(x => x.UserName)
                    @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.UserName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.Email)
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", type = "email" })
                    @Html.ValidationMessageFor(x => x.Email)
                </div>

                @if (!Model.DisableFileUploads)
                {
                    <div class="row membereditavatar">
                        <div class="col-md-2">
                            <img src="@AppHelpers.MemberImage(Model.Avatar, Model.Email, Model.Id, SiteConstants.GravatarProfileSize)" alt="@Model.UserName">
                        </div>
                        <div class="col-md-10">
                            @Html.LabelFor(x => x.Files)
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <span class="btn btn-default btn-file">
                                        @Html.LanguageString("Post.Browse") <input type="file" name="files" id="files" value="">
                                    </span>
                                </span>
                                <input type="text" class="form-control" readonly="">
                            </div>
                            @Html.ValidationMessageFor(x => x.Files)
                        </div>
                    </div>
                }

                <div class="form-group">
                    @Html.LabelFor(x => x.Age)
                    @Html.TextBoxFor(x => x.Age, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Age)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.Location)
                    @Html.TextBoxFor(x => x.Location, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Location)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.Website)
                    @Html.TextBoxFor(x => x.Website, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Website)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.Twitter)
                    @Html.TextBoxFor(x => x.Twitter, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Twitter)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.Facebook)
                    @Html.TextBoxFor(x => x.Facebook, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Facebook)
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.Signature)
                    @Html.TextAreaFor(x => x.Signature, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Signature)
                </div>
                
                <div class="checkbox">
                    @using (Html.BeginLabelFor(m => m.DisableEmailNotifications, new { @class = "checkbox" }))
                    {
                        @Html.CheckBoxFor(m => m.DisableEmailNotifications)
                    }
                    @Html.ValidationMessageFor(m => m.DisableEmailNotifications)
                </div>

                <div class="submit-holder">
                    <button type="submit" class="btn-mvc-green btn-mvc-large">@Html.LanguageString("Buttons.Save")</button>
                </div>
            </fieldset>
        }

    </div>
</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/Members/ForgotPassword.cshtml
@model MVCForum.Website.ViewModels.ForgotPasswordViewModel
@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("Members.ForgotPassword.Title");
}

<div class="row">

    <div class="col-md-6 col-md-offset-3">

        @using (Html.BeginForm("ForgotPassword", "Members", FormMethod.Post, new { @class = "form-forgotpassword" }))
        {

            @Html.ValidationSummary(true)
            @Html.AntiForgeryToken()

            <h3>@ViewBag.Title</h3>

            <div class="form-group">
                @Html.LabelFor(m => m.EmailAddress)
                @Html.TextBoxFor(m => m.EmailAddress, new { @class="form-control", type="email" })
                @Html.ValidationMessageFor(m => m.EmailAddress)
            </div>

            <div class="submit-holder">
                <button type="submit" class="btn-mvc-green btn-mvc-large">@Html.LanguageString("Buttons.ResetPassword")</button>
            </div>

        }

    </div>

</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/Members/GetCurrentActiveMembers.cshtml
@using MVCForum.Website
@model MVCForum.Website.ViewModels.ActiveMembersViewModel

<div class="active-members">
    <h6>@Html.LanguageString("Stats.FooterActiveUsersText")</h6>
    @if (Model.ActiveMembers.Any())
    {
        <ul class="activememberslist">
            @foreach (var member in Model.ActiveMembers)
            {
                <li>
                    <a title="@Html.Raw(member.UserName)" href="@member.NiceUrl">
                        <img src="@member.MemberImage(SiteConstants.GravatarLeaderboardSize)" alt="@Html.Raw(member.UserName)" />
                    </a>
                </li>
            }
        </ul>
    }
    else
    {
        <p>@Html.Lang("Notifications.NoActiveMembers")</p>
    }
</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/Members/LogOn.cshtml
@using MVCForum.Website.Application.ExtensionMethods
@model MVCForum.Website.ViewModels.LogOnViewModel
@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("LogOn.LogOn");
}

<div class="row">

    <div class="col-md-6 col-md-offset-3">

        @Html.Partial("_SocialLoginButtons")


        <div class="mainlogonform">

            <h3>@ViewBag.Title</h3>

            @using (Html.BeginForm("LogOn", "Members", FormMethod.Post, new { @class = "form-login" }))
            {
                @Html.ValidationSummary(false)
                @Html.AntiForgeryToken()

                <p class="help-block">@Html.Raw(string.Format(Html.LanguageString("Members.LogOnMessage"), Html.ActionLink("Register", "Register")))</p>

                <div class="form-group">
                    @Html.LabelFor(m => m.UserName)
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.UserName)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Password)
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Password)
                </div>

                <div class="checkbox">
                    @using (Html.BeginLabelFor(m => m.RememberMe, new { @class = "checkbox" }))
                    {
                        @Html.CheckBoxFor(m => m.RememberMe)
                    }
                    @Html.ValidationMessageFor(m => m.RememberMe)
                </div>

                <div class="submit-holder">
                    <button type="submit" class="btn-mvc-green btn-mvc-large">@Html.LanguageString("Buttons.LogOn")</button>
                </div>

                @Html.HiddenFor(x => x.ReturnUrl)
            }
        </div>

        <p class="forgotpasswordtext">
            <a href="@Url.Action("ForgotPassword")">
                @Html.LanguageString("Members.ForgotPassword.Link")
            </a>
        </p>

    </div>

</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/Members/PasswordChanged.cshtml
@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("Members.ChangePassword.Success");
}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="mainheading">
            <h1>@ViewBag.Title</h1>
        </div>
        <p>@Html.LanguageString("Members.ResetPassword.SuccessText")</p>
        <p>@Html.ActionLink(Html.Lang("Layout.Nav.Logon"), "LogOn", "Members", null, new { @class = "btn-mvc-green btn-mvc-large" })</p>
    </div>
</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/Members/Register.cshtml
@using MVCForum.Utilities
@model MVCForum.Website.ViewModels.MemberAddViewModel
@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("Members.Register");
}

@if (!User.Identity.IsAuthenticated)
{

    <div class="row">

        <div class="col-md-6 col-md-offset-3">

            @Html.Partial("_SocialLoginButtons")

            <div class="mainregisterform">

                <h3>@ViewBag.Title</h3>

                @using (Html.BeginForm("Register", "Members", FormMethod.Post, new { @class = "form-register" }))
                {
                    @Html.ValidationSummary(true)
                    @Html.AntiForgeryToken()
                    
                    <div class="form-group">
                        @Html.LabelFor(x => Model.UserName)
                        @Html.TextBoxFor(x => Model.UserName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.UserName)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => Model.Password)
                        @Html.PasswordFor(x => Model.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Password)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => Model.ConfirmPassword)
                        @Html.PasswordFor(x => Model.ConfirmPassword, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.ConfirmPassword)
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => x.Email)
                        @Html.TextBoxFor(x => x.Email, new { type = "email", @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Email)
                    </div>

                    if (!string.IsNullOrEmpty(Html.Settings().SpamQuestion))
                    {
                        <div class="form-group">
                            <label for="SpamAnswer">@Html.Settings().SpamQuestion</label>
                            @Html.TextBoxFor(x => x.SpamAnswer, new { @class = "form-control" })
                        </div>
                    }

                    <div class="submit-holder">
                        <button type="submit" class="btn-mvc-green btn-mvc-large">
                            @Html.LanguageString("Members.Register")
                        </button>
                    </div>

                    @Html.HiddenFor(x => x.ReturnUrl)
                }
            </div>

        </div>

    </div>
}
else
{
    <p>@Html.LanguageString("Members.AlreadyRegistered")</p>
}

N05~Forum/N05~Forum/MVCForum.Website/Views/Members/SideAdminPanel.cshtml
@model MVCForum.Website.ViewModels.ViewAdminSidePanelViewModel

@if (Model.IsDropDown)
{
    <li class="dropdown">
        <a href="#" class="dropdown-toggle mytoolslink" data-toggle="dropdown">
            @Html.LanguageString("SideBox.MyTools")
            @if (Model.NewPrivateMessageCount > 0)
            {
                <span class="badge">@Model.NewPrivateMessageCount</span>
            }
            else
            {
                <span class="caret"></span>
            }
        </a>
        <ul class="dropdown-menu" role="menu">
            @Html.Raw(DropDownContents())
        </ul>
    </li>
}
else
{
    @Html.Raw(DropDownContents())
}



@helper DropDownContents()
{
    if (User.IsInRole(AppConstants.AdminRoleName))
    {
        <li><a href="@Url.Action("Index", "Admin", new {area = "Admin"}, null)">@Html.LanguageString("Layout.Nav.Admin")</a></li>
    }
    <li>@Html.ActionLink(Html.LanguageString("Members.SearchMembers"), "Search", "Members")</li>
    <li>
        <a href="@Url.Action("Edit", "Members", new { id = Model.CurrentUser.Id })">@Html.LanguageString("Buttons.Edit") @Model.CurrentUser.UserName</a>
    </li>
    if (Model.CanViewPrivateMessages)
    {
        <li>
            <a href="@Url.Action("Index", "PrivateMessage")">
                @Html.LanguageString("PM.PrivateMessages")
                @if (Model.NewPrivateMessageCount > 0)
                {
                    <span class="badge">@Model.NewPrivateMessageCount</span>
                }
            </a>
        </li>
    }

    <li>@Html.ActionLink(Html.LanguageString("LogOn.LogOff"), "LogOff", "Members")</li>
}