N05~Forum/N05~Forum/MVCForum.Website/ViewModels/LanguageViewModels.cs
using System;
using System.Collections.Generic;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.ViewModels
{
    public class LanguageListAllViewModel
    {
        public IEnumerable<Language> Alllanguages { get; set; }
        public Guid CurrentLanguage { get; set; }
    }
}

N05~Forum/N05~Forum/MVCForum.Website/Areas/Admin/Controllers/ImportExportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.Application;
using MVCForum.Website.Areas.Admin.ViewModels;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public partial class ImportExportController : BaseAdminController
    {
        private readonly ILocalizationService _localizationService;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="unitOfWorkManager"> </param>
        /// <param name="membershipService"> </param>
        /// <param name="localizationService"></param>
        /// <param name="settingsService"> </param>
        /// <param name="loggingService"> </param>
        public ImportExportController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, 
            IMembershipService membershipService, ILocalizationService localizationService, ISettingsService settingsService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, settingsService)
        {
            _localizationService = localizationService;
        }

        #region Private methods

        /// <summary>
        /// Convert an import report into JSON data
        /// </summary>
        /// <param name="report"></param>
        /// <returns></returns>
        private static object ToJSON(CsvReport report)
        {
            var oSerializer = new JavaScriptSerializer();
            var json = new
            {
                HasErrors = report.Errors.Any(),
                HasWarnings = report.Warnings.Any(),
                Warnings = oSerializer.Serialize(report.Warnings.ExtractMessages()),
                Errors = oSerializer.Serialize(report.Errors.ExtractMessages()),
            };

            return json;
        }


        #endregion

        /// <summary>
        /// We get here via the admin default layout (_AdminLayout). The returned view is displayed by
        /// the @RenderBody in that layout
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Export a language in csv format
        /// </summary>
        /// <returns></returns>
        public CsvFileResult ExportUsers()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                return new CsvFileResult { FileDownloadName = "MVCForumUsers.csv", Body = MembershipService.ToCsv() };
            }
        }

        /// <summary>
        /// Post of data for users import (file info)
        /// </summary>
        /// <param name="file">The name-value pairs for the language content</param>
        /// <returns></returns>
        [HttpPost]
        public WrappedJsonResult ImportUsers(HttpPostedFileBase file)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var report = new CsvReport();

                //http://www.dustinhorne.com/post/2011/11/16/AJAX-File-Uploads-with-jQuery-and-MVC-3.aspx
                try
                {
                    // Verify that the user selected a file
                    if (file != null && file.ContentLength > 0)
                    {
                        // Unpack the data
                        var allLines = new List<string>();
                        using (var streamReader = new StreamReader(file.InputStream, System.Text.Encoding.UTF8, true))
                        {
                            while (streamReader.Peek() >= 0)
                            {
                                allLines.Add(streamReader.ReadLine());
                            }
                        }

                        // Read the CSV file and generate a language
                        report = MembershipService.FromCsv(allLines);
                        unitOfWork.Commit();
                    }
                    else
                    {
                        report.Errors.Add(new CsvErrorWarning
                        {
                            ErrorWarningType = CsvErrorWarningType.BadDataFormat,
                            Message = "File does not contain any users."
                        });
                    }
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    report.Errors.Add(new CsvErrorWarning
                    {
                        ErrorWarningType = CsvErrorWarningType.GeneralError,
                        Message = string.Format("Unable to import users: {0}", ex.Message)
                    });
                }

                return new WrappedJsonResult { Data = ToJSON(report) };
            }
        }

        /// <summary>
        /// Export a language in csv format
        /// </summary>
        /// <param name="languageCulture"></param>
        /// <returns></returns>
        public CsvFileResult ExportLanguage(string languageCulture)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var csv = new CsvFileResult();

                var language = _localizationService.GetLanguageByLanguageCulture(languageCulture);

                if (language != null)
                {
                    csv.FileDownloadName = languageCulture + ".csv";
                    csv.Body = _localizationService.ToCsv(language);
                }
                else
                {
                    csv.Body = "No such language";
                    LoggingService.Error("No such language when trying to export language");
                }

                return csv; 
            }
        }

        /// <summary>
        /// Post of data for language import (file info)
        /// </summary>
        /// <param name="languageCulture">This defines the name etc of the imported language</param>
        /// <param name="file">The name-value pairs for the language content</param>
        /// <returns></returns>
        [HttpPost]
        public WrappedJsonResult ImportLanguage(string languageCulture, HttpPostedFileBase file)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var report = new CsvReport();

                //http://www.dustinhorne.com/post/2011/11/16/AJAX-File-Uploads-with-jQuery-and-MVC-3.aspx
                try
                {
                    // Verify that the user selected a file
                    if (file != null && file.ContentLength > 0)
                    {
                        // Unpack the data
                        var allLines = new List<string>();
                        using (var streamReader = new StreamReader(file.InputStream, System.Text.Encoding.UTF8, true))
                        {
                            while (streamReader.Peek() >= 0)
                            {
                                allLines.Add(streamReader.ReadLine());
                            }
                        }

                        // Read the CSV file and generate a language
                        report = _localizationService.FromCsv(languageCulture, allLines);
                        unitOfWork.Commit();
                    }
                    else
                    {
                        report.Errors.Add(new CsvErrorWarning
                        {
                            ErrorWarningType = CsvErrorWarningType.BadDataFormat,
                            Message = "File does not contain a language."
                        });
                    }
                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    report.Errors.Add(new CsvErrorWarning
                    {
                        ErrorWarningType = CsvErrorWarningType.GeneralError,
                        Message = string.Format("Unable to import language: {0}", ex.Message)
                    });
                }

                return new WrappedJsonResult { Data = ToJSON(report) }; 
            }
        }

        public ActionResult Languages()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var importExportViewModel = new LanguagesHomeViewModel();

                // For languages we need a list of export languages and import languages
                var languageImportExportViewModel = new LanguageImportExportViewModel
                {
                    ExportLanguages = _localizationService.LanguagesInDb,
                    ImportLanguages = _localizationService.LanguagesAll
                };
                importExportViewModel.LanguageViewModel = languageImportExportViewModel;

                return View(importExportViewModel);
            }
        }

        public ActionResult Members()
        {
            return View();
        }
    }
}

N05~Forum/N05~Forum/MVCForum.Website/Controllers/LanguageController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.ViewModels;

namespace MVCForum.Website.Controllers
{
    public partial class LanguageController : BaseController
    {
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="unitOfWorkManager"> </param>
        /// <param name="membershipService"></param>
        /// <param name="localizationService"></param>
        /// <param name="roleService"></param>
        /// <param name="settingsService"> </param>
        /// <param name="loggingService"> </param>
        public LanguageController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService, 
            IRoleService roleService, ISettingsService settingsService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            
        }

        /// <summary>
        /// Lists out all languages in a partial view. For example, used to display list of 
        /// available languages along the top of every page
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        public ActionResult Index()
        {
            var viewModel = new LanguageListAllViewModel
            {
                Alllanguages = LocalizationService.AllLanguages,
                CurrentLanguage = LocalizationService.CurrentLanguage.Id
            };
            if (viewModel.Alllanguages.Count() <= 1)
            {
                return Content(string.Empty);
            }
            return PartialView("_LanguagePartial", viewModel);
        }

        /// <summary>
        /// Change the current language (typically called from each language link generated in this controller's index method)
        /// </summary>
        /// <param name="lang"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ChangeLanguage(Guid lang)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var language = LocalizationService.Get(lang);
                LocalizationService.CurrentLanguage = language;

                // The current language is stored in a cookie
                var cookie = new HttpCookie(AppConstants.LanguageIdCookieName)
                {
                    HttpOnly = false,
                    Value = language.Id.ToString(),
                    Expires = DateTime.UtcNow.AddYears(1)
                };

                Response.Cookies.Add(cookie);

                //TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                //{
                //    Message = LocalizationService.GetResourceString("Language.Changed"),
                //    MessageType = GenericMessages.success
                //};

                return Content("success"); 
            }
        }
    }
}

N05~Forum/N05~Forum/MVCForum.Website/Areas/Admin/Views/ImportExport/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Import / Export</h2>
<p>This section provides several bulk features to help administrate and build your forum</p>

<div class="panel panel-default">
    <div class="panel-body">
        <h3>Languages</h3>
        <p>Export languages edit and re-import, or import a new languages</p>
        <a href="@Url.Action("Languages", "ImportExport", new { area = "Admin" }, null)" class="btn btn-large">Go to Languages</a>

    </div>
</div>


<div class="panel panel-default">
    <div class="panel-body">
        <h3>Members</h3>
        <p>Export all members, or import members from another forum</p>
        <a href="@Url.Action("Members", "ImportExport", new { area = "Admin" }, null)" class="btn btn-large">Go to Members</a>

    </div>
</div>

N05~Forum/N05~Forum/MVCForum.Website/Areas/Admin/Views/ImportExport/Languages.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.LanguagesHomeViewModel

@{
    ViewBag.Title = "Languages";
}


<div class="panel panel-default">
    <div class="panel-body">
        <h2>Export a Language</h2>
        <p>Exports the language into CSV</p>
        @using (Html.BeginForm("ExportLanguage", "ImportExport"))
        {
            <p>@Html.DropDownList("languageCulture", new SelectList(@Model.LanguageViewModel.ExportLanguages, "Name", "EnglishName"), new { @class = "form-control" })</p>
            <div class="submit-holder">
                <button type="submit" class="btn-mvc-green">Export</button>
            </div>
        }
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body">
        <h2>Import a Language</h2>
        <p>Import a language from a CSV file, making sure you choose the correct language from the drop down. Use the export language option above to get a template for the import.</p>
        @using (Html.BeginForm("ImportLanguage", "ImportExport", FormMethod.Post, new { enctype = "multipart/form-data", id = "ImportForm", name = "ImportForm", target = "UploadTarget" }))
        {
            <p>@Html.DropDownList("languageCulture", new SelectList(@Model.LanguageViewModel.ImportLanguages, "Name", "EnglishName"), new { @class = "form-control" })</p>
            <div class="submit-holder form-group">
                <p><input type="file" id="file" name="file" class="form-control" /></p>
                <p><input type="submit" class="btn-mvc-green" value="Import" /></p>
            </div>
        }

        @*Results of any import are displayed here:*@
        <div id="ImportResults"></div>

        @*This frame is displayed off the page and gets the results of the import (ie the success or fail messages) *@
        <iframe id="UploadTarget" name="UploadTarget" onload="Import_Complete();" style="position: absolute; left: -999em; top: -999em;"></iframe>

    </div>
</div>

N05~Forum/N05~Forum/MVCForum.Website/Areas/Admin/Views/ImportExport/Members.cshtml
@{
    ViewBag.Title = "Import / Export Members";
}

<div class="row">
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h5>Export Members</h5>
            </div>
            <div class="panel-body">
                <p>Export all members into a CSV, you can use this CSV format to also import members into the forum.</p>
                @using (Html.BeginForm("ExportUsers", "ImportExport"))
                {
                    <div class="submit-holder">
                        <button type="submit" class="btn-mvc-green">Export</button>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel">
            <div class="panel-heading">
                <h5>Import Members</h5>
            </div>
            <div class="panel-content">
                <p>The easiest way to find out what format the CSV file to import should be in, is to click the export button above and use that as a template.</p>
                @using (Html.BeginForm("ImportUsers", "ImportExport", FormMethod.Post, new { enctype = "multipart/form-data", id = "ImportForm", name = "ImportForm", target = "UploadTarget" }))
                {
                    <div class="submit-holder">
                        <p><input type="file" id="file" name="file" /></p>
                        <p><input type="submit" class="btn-mvc-green" value="Import" /></p>
                    </div>
                }

                @*Results of any import are displayed here:*@
                <div id="ImportResults"></div>

                @*This frame is displayed off the page and gets the results of the import (ie the success or fail messages) *@
                <iframe id="UploadTarget" name="UploadTarget" onload="Import_Complete();" style="position: absolute; left: -999em; top: -999em;"></iframe>
            </div>
        </div>
    </div>
</div>