N05~Forum/N05~Forum/MVCForum.Website/ViewModels/PrivateMessageViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces;
using MVCForum.Website.Application;

namespace MVCForum.Website.ViewModels
{

    public class ListPrivateMessageViewModel
    {
        public IList<PrivateMessageListItem> Messages { get; set; }
        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
        public int TotalPages { get; set; }
    }

    public class CreatePrivateMessageViewModel
    {
        [UIHint(SiteConstants.EditorType), AllowHtml]
        public string Message { get; set; }

        [ForumMvcResourceDisplayName("PM.RecipientUsername")]
        [Required]
        public Guid To { get; set; }

    }

    public class ViewPrivateMessageViewModel
    {
        public IPagedList<PrivateMessage> PrivateMessages { get; set; } 
        public MembershipUser From { get; set; }
        public bool FromUserIsOnline { get; set; }
        public bool IsAjaxRequest { get; set; }
        public bool IsBlocked { get; set; }
    }

    public class DeletePrivateMessageViewModel
    {
        public Guid Id { get; set; }
    }


    public class GetMoreViewModel
    {
        public Guid UserId { get; set; }
        public int PageIndex { get; set; }
    }


}

N05~Forum/N05~Forum/MVCForum.Website/Controllers/PrivateMessageController.cs
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Utilities;
using MVCForum.Website.Application;
using MVCForum.Website.Areas.Admin.ViewModels;
using MVCForum.Website.ViewModels;
using MVCForum.Website.ViewModels.Mapping;

namespace MVCForum.Website.Controllers
{
    [Authorize]
    public partial class PrivateMessageController : BaseController
    {
        private readonly IPrivateMessageService _privateMessageService;
        private readonly IEmailService _emailService;

        public PrivateMessageController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService,
            ILocalizationService localizationService, IRoleService roleService, ISettingsService settingsService, IPrivateMessageService privateMessageService,
            IEmailService emailService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _privateMessageService = privateMessageService;
            _emailService = emailService;
        }

        public ActionResult Index(int? p)
        {
            if (LoggedOnReadOnlyUser.DisablePrivateMessages == true)
            {
                TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = LocalizationService.GetResourceString("Errors.NoPermission"),
                    MessageType = GenericMessages.danger
                };
                return RedirectToAction("Index", "Home");
            }
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var pageIndex = p ?? 1;
                var pagedMessages = _privateMessageService.GetUsersPrivateMessages(pageIndex, SiteConstants.PrivateMessageListSize, LoggedOnReadOnlyUser);
                var viewModel = new ListPrivateMessageViewModel
                {
                    Messages = pagedMessages,
                    PageIndex = pageIndex,
                    TotalCount = pagedMessages.TotalCount,
                    TotalPages = pagedMessages.TotalPages
                };
                return View(viewModel);
            }
        }

        [ChildActionOnly]
        public ActionResult Create(Guid to)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new CreatePrivateMessageViewModel
                {
                    To = to
                };

                try
                {
                    var permissions = RoleService.GetPermissions(null, UsersRole);
                    var settings = SettingsService.GetSettings();
                    // Check if private messages are enabled
                    if (!settings.EnablePrivateMessages || LoggedOnReadOnlyUser.DisablePrivateMessages == true)
                    {
                        return Content(LocalizationService.GetResourceString("Errors.GenericMessage"));
                    }

                    // Check outbox size of logged in user
                    var senderCount = _privateMessageService.GetAllSentByUser(LoggedOnReadOnlyUser.Id).Count;
                    if (senderCount > settings.MaxPrivateMessagesPerMember)
                    {
                        return Content(LocalizationService.GetResourceString("PM.SentItemsOverCapcity"));
                    }
                    if (senderCount > (settings.MaxPrivateMessagesPerMember - SiteConstants.PrivateMessageWarningAmountLessThanAllowedSize))
                    {
                        // Send user a warning they are about to exceed 
                        var sb = new StringBuilder();
                        sb.AppendFormat("<p>{0}</p>", LocalizationService.GetResourceString("PM.AboutToExceedInboxSizeBody"));
                        var email = new Email
                        {
                            EmailTo = LoggedOnReadOnlyUser.Email,
                            NameTo = LoggedOnReadOnlyUser.UserName,
                            Subject = LocalizationService.GetResourceString("PM.AboutToExceedInboxSizeSubject")
                        };
                        email.Body = _emailService.EmailTemplate(email.NameTo, sb.ToString());
                        _emailService.SendMail(email);
                    }

                    // Set editor permissions
                    ViewBag.ImageUploadType = permissions[AppConstants.PermissionInsertEditorImages].IsTicked ? "forumimageinsert" : "image";

                    unitOfWork.Commit();

                }
                catch (Exception ex)
                {
                    unitOfWork.Rollback();
                    LoggingService.Error(ex);
                }

                return PartialView(viewModel);
            }

        }

        [HttpPost]
        public ActionResult Create(CreatePrivateMessageViewModel createPrivateMessageViewModel)
        {
            var settings = SettingsService.GetSettings();
            if (!settings.EnablePrivateMessages || LoggedOnReadOnlyUser.DisablePrivateMessages == true)
            {
                throw new Exception(LocalizationService.GetResourceString("Errors.GenericMessage"));
            }
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                if (ModelState.IsValid)
                {
                    var loggedOnUser = MembershipService.GetUser(LoggedOnReadOnlyUser.Id);
                    var memberTo = MembershipService.GetUser(createPrivateMessageViewModel.To);

                    // Check the user they are trying to message hasn't blocked them
                    if (loggedOnUser.BlockedByOtherUsers.Any(x => x.Blocker.Id == memberTo.Id))
                    {
                        return Content(PmAjaxError(LocalizationService.GetResourceString("PM.BlockedMessage")));
                    }

                    // Check flood control
                    var lastMessage = _privateMessageService.GetLastSentPrivateMessage(LoggedOnReadOnlyUser.Id);
                    // If this message they are sending now, is to the same person then ignore flood control
                    if (lastMessage != null && createPrivateMessageViewModel.To != lastMessage.UserTo.Id)
                    {
                        if (DateUtils.TimeDifferenceInSeconds(DateTime.UtcNow, lastMessage.DateSent) < settings.PrivateMessageFloodControl)
                        {
                            return Content(PmAjaxError(LocalizationService.GetResourceString("PM.SendingToQuickly")));
                        }
                    }

                    // first check they are not trying to message themself!
                    if (memberTo != null)
                    {
                        // Map the view model to message
                        var privateMessage = new PrivateMessage
                        {
                            UserFrom = loggedOnUser,
                            Message = createPrivateMessageViewModel.Message,
                        };

                        // Check settings
                        if (settings.EnableEmoticons == true)
                        {
                            privateMessage.Message = EmoticonUtils.Emotify(privateMessage.Message);
                        }

                        // check the member
                        if (!String.Equals(memberTo.UserName, LoggedOnReadOnlyUser.UserName, StringComparison.CurrentCultureIgnoreCase))
                        {
                            // Check in box size for both
                            var receiverCount = _privateMessageService.GetAllReceivedByUser(memberTo.Id).Count;
                            if (receiverCount > settings.MaxPrivateMessagesPerMember)
                            {
                                return  Content(string.Format(LocalizationService.GetResourceString("PM.ReceivedItemsOverCapcity"), memberTo.UserName));
                            }

                            // If the receiver is about to go over the allowance them let then know too
                            if (receiverCount > (settings.MaxPrivateMessagesPerMember - SiteConstants.PrivateMessageWarningAmountLessThanAllowedSize))
                            {
                                // Send user a warning they are about to exceed 
                                var sb = new StringBuilder();
                                sb.AppendFormat("<p>{0}</p>", LocalizationService.GetResourceString("PM.AboutToExceedInboxSizeBody"));
                                var email = new Email
                                {
                                    EmailTo = memberTo.Email,
                                    NameTo = memberTo.UserName,
                                    Subject = LocalizationService.GetResourceString("PM.AboutToExceedInboxSizeSubject")
                                };
                                email.Body = _emailService.EmailTemplate(email.NameTo, sb.ToString());
                                _emailService.SendMail(email);
                            }

                            // Good to go send the message!
                            privateMessage.UserTo = memberTo;
                            _privateMessageService.Add(privateMessage);

                            try
                            {
                                // Finally send an email to the user so they know they have a new private message
                                // As long as they have not had notifications disabled
                                if (memberTo.DisableEmailNotifications != true)
                                {
                                    var email = new Email
                                    {

N05~Forum/N05~Forum/MVCForum.Website/Views/PrivateMessage/AjaxMore.cshtml
@model MVCForum.Website.ViewModels.ViewPrivateMessageViewModel

@foreach (var pm in Model.PrivateMessages)
{
    @Html.Partial("_PrivateMessage", pm)
}

N05~Forum/N05~Forum/MVCForum.Website/Views/PrivateMessage/Create.cshtml
@model MVCForum.Website.ViewModels.CreatePrivateMessageViewModel

<div id="createpostholder">
    @using (Ajax.BeginForm("Create", "PrivateMessage", null, new AjaxOptions
        {
            HttpMethod = "POST",
            LoadingElementId = "createpostwait",
            OnSuccess = "AjaxPrivateMessageSuccess()",
            OnFailure = "AjaxPostError('Error creating private message')",
            UpdateTargetId = "newpmmarker",
            OnBegin = "AjaxPostBegin()"
        }, new { @id = "postcodeform", @class = "form-createpm" }))
    {
        <div class="editorholder">
            @Html.EditorFor(x => x.Message, new { @class = "createpm required rte" })
            @Html.ValidationMessageFor(x => x.Message)
        </div>
        <input type="submit" id="createpmbutton" class="btn-mvc-green btn-mvc-large" value="@Html.LanguageString("PM.Send")" />
        <span style="display: none;" id="createpostwait" class="ajaxspinner" title="@Html.LanguageString("Post.PleaseWait")">@Html.LanguageString("Post.PleaseWait")</span>
        @Html.HiddenFor(x => x.To)
    }
</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/PrivateMessage/Index.cshtml
@model MVCForum.Website.ViewModels.ListPrivateMessageViewModel

@{
    Layout = "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = Html.LanguageString("PM.ReceivedPrivateMessages");
}
<div class="row">

    <div class="col-md-8 col-md-offset-2">
        <div class="privatemessages">

            <h2>@ViewBag.Title</h2>

            @if (Model.Messages.Any())
            {
                <table class="table table-bordered table-striped table-adaptive">
                    <thead>
                        <tr>
                            <th>@Html.LanguageString("PM.From")</th>
                            <th>@Html.LanguageString("PM.LastActivity")</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var message in Model.Messages)
                        {
                            <tr>
                                <td>
                                    <a href="@Url.Action("View", new { from = message.User.Id })" class="pm-panel" data-name="@string.Concat(Html.Lang("PM.Title"), message.User.UserName)">
                                        <strong>
                                            @message.User.UserName 
                                        </strong>
                                    </a>
                                    @if (message.HasUnreadMessages){<text><i class="fa fa-commenting-o newmessageicon"></i></text>}
                                </td>
                                <td>
                                    @DatesUI.GetPrettyDate(message.Date.ToString())
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                if (Model.TotalPages > 1)
                {
                    @Html.Pager(Convert.ToInt32(Model.PageIndex), SiteConstants.PrivateMessageListSize, Convert.ToInt32(Model.TotalCount), new { })
                }
            }
            else
            {
                <p>@Html.LanguageString("PM.NoMessages")</p>
            }
        </div>
    </div>
</div>

N05~Forum/N05~Forum/MVCForum.Website/Views/PrivateMessage/View.cshtml
@model MVCForum.Website.ViewModels.ViewPrivateMessageViewModel
@{
    Layout = Model.IsAjaxRequest ? "" : "~/Views/Shared/_LayoutFullWidth.cshtml";
    ViewBag.Title = string.Concat(Html.LanguageString("PM.Title"), Model.From.UserName);
}

<div class="pmview">
    <div class="row">

        <div class="@(Model.IsAjaxRequest ? "col-md-12" : "col-md-8 col-md-offset-2")">            
            @if (!Model.IsAjaxRequest)
            {
                <div class="btn-group top-pm-nav">
                    @Html.ActionLink(Html.LanguageString("PM.BackToInbox"), "Index", new { }, new { @class = "btn-mvc btn-mvc-green" })
                </div>
                <h1>
                    <a href="@Model.From.NiceUrl">
                        <img src="@Model.From.MemberImage(SiteConstants.GravatarPostSize)" alt="@Model.From.UserName" class="pmavatar" /> @Model.From.UserName
                        @if (Model.FromUserIsOnline)
                        {
                            <span class="label label-success">@Html.Lang("PM.MemberIsOnline")</span>
                        }
                    </a>
                </h1>
            }
            <ul class="pmadminav">
                <li>
                    <a href="#" class="btn-mvc pm-block" data-userid="@Model.From.Id" data-blocktext="@Html.Lang("PM.Block") @Model.From.UserName" data-isblocked="@Model.IsBlocked.ToString().ToLower()" data-blockedtext="@Html.Lang("PM.Blocked") @Model.From.UserName">                        
                        @(Model.IsBlocked ? Html.Lang("PM.Blocked") : Html.Lang("PM.Block")) @Model.From.UserName
                    </a>
                </li>
                @if (Html.Settings().EnableMemberReporting)
                {
                    <li><a href="@Url.Action("Report", "Members", new { id = Model.From.Id }, null)" class="btn-mvc">@Html.LanguageString("Buttons.Report")</a></li>
                }
                @if (Model.FromUserIsOnline)
                {
                    <li>
                        <span class="label label-success">@Html.Lang("PM.MemberIsOnline")</span>
                    </li>
                }
            </ul>
            <div class="createmessageholder">
                @Html.Action("Create", new {to = Model.From.Id})
            </div>
            
            <div class="privatemessages">
                <span id="newpmmarker"></span>
                @foreach (var pm in Model.PrivateMessages)
                {
                    @Html.Partial("_PrivateMessage", pm)
                }
                @if (Model.PrivateMessages.TotalPages > 1)
                {
                    <a href="#" class="showmorepms btn-mvc btn-mvc-large btn-mvc-fullwidth">
                        <span class="smpmactive">@Html.LanguageString("PM.ShowMore")</span>
                        <span class="smpmloading" style="display: none;">@Html.LanguageString("PM.ShowMoreLoading")</span>
                    </a>
                }
            </div>
        </div>
    </div>
    <input type="hidden" id="pageIndex" value="@(Model.PrivateMessages.PageIndex + 1)" />
    <input type="hidden" id="userId" value="@Model.From.Id" />
    <input type="hidden" id="totalPages" value="@Model.PrivateMessages.TotalPages" />
</div>